### ISSUE TITLE
Selectively apply "text-align-last: justify;" when a paragraph breaks across pages

### ISSUE THREAD

**Issue by ghost** [marvindanig/pinocchio#3]
Take a look at pages [19 and 20.](http://localhost:4567/#24) The last paragraph on page 19 overflows to page 20 and needs to have the last line justified. We can achieve this with:
`p:last-child {
  text-align: justify;
  -moz-text-align-last: justify;
  text-align-last: justify;
}`

Adding this rule to the template is problematic, because it affects all last-child paragraphs and justification on the last paragraph of page 20 looks horrible. How do we select only last-child paragraphs that break across a page? I could add a few lines of code to the knead tool to write style.css pages with this rule, but some CSS magic in the template would be a much better solution.

**Comment by marvindanig** [comment]
hmm. I'm gonna sit on this one tonight...

**Comment by marvindanig** [comment]
Okay, so I see you made a [few changes](https://github.com/marvindanig/The-Adventures-Of-Pinocchio/commits/fa81d2cbf26e22ebeafa86ba83b634e7dcdf815a/templates) to the template_CSS, such as having margin/padding inside every leaf to push the inner container around and also to squeeze its content. 

I'm afraid this is not going to work/scale correctly because display:flex is supposed to do that; and that is why no margins/paddings were hardcoded to begin with! Flex `align-items:center` and `justify-content` takes care of horizontal _and_ vertical centerization of content.

I suspect this would also make handling overflows harder because then we'd need to introduce another CSS hack to guarantee edge cases work properly -- and then follow it through with testing the behavior on 80 different devices out there -- my thought is that it will be virtually impossible to peruse this path  when we're pitched with more complicated HTML with images/embeds/videos etc. 

Can I take a look at how we got to the spot of introducing margins/additional into template css before making final conclusions. I sent you a mail separately.

**Comment by marvindanig** [comment]
Craig can we remove the page numbers from the content and check the manuscript back again?

**Comment by ghost** [comment]
[changes reverted](https://github.com/marvindanig/The-Adventures-Of-Pinocchio/commit/b5bd51be72fb2e1aaadf8eb6f72cc368ff35d198)
